## Exercise 1

a) Consider the following dynamical system 

$$
x_{n+1} = 
\begin{cases} 
    -x_n + 1 + u_n & \text{if } -2 \leq -x_n + 1 + u_n \leq 2 \\
    2 & \text{if } -x_n + 1 + u_n > 2 \\
    -2 & \text{else}
\end{cases}
$$

where $ x_n \in \{-2, -1, 0, 1, 2\} $ and $ u_n \in \{-1, 0, 1\} $, and the cost function

$$
J = \sum_{k=0}^2 \left( 2|x_k| + |u_k| \right) + x_3^2

$$

Use the dynamic programming algorithm to solve the finite horizon optimal control problem that minimizes \( J \). Show the different steps of the algorithm and present the results in a table including the cost-to-go and the optimal control at every stage.



In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Solution:$\\$
Given: $ J = \sum_{k=0}^2 \left( 2|x_k| + |u_k| \right) + x_3^2 $, $ x_n \in \{-2, -1, 0, 1, 2\} $ and $ u_n \in \{-1, 0, 1\} $

In [18]:
u=np.array([-1, 0, 1])
x=np.array([-2,-1,0,1,2])

u2=np.zeros(5)
u1=np.zeros(5)
u0=np.zeros(5)
J2=np.zeros(5)
J1=np.zeros(5)
J0=np.zeros(5)

J3=[]
for i in x:
    i*=i
    J3.append(i)
    
data3 = {
    'x3': x,
    'J3': J3
}

df_J3 = pd.DataFrame(data3)   
print(df_J3)
print(J2)

   x3  J3
0  -2   4
1  -1   1
2   0   0
3   1   1
4   2   4
[0. 0. 0. 0. 0.]


In [19]:
L=[]
iteration=0
for l in x:
   print("_______________________________________________________________")
   print(f"At x2 = {l}")
   for k in u:
       l2=-1*(l)+1+k
       if l2>2:
           l2=2
           L.append(int(l2))
       elif l2<-2:
           l2=-2
           L.append(int(l2))
       else:
           L.append(int(l2)) 
    
   print(f"x3 set for J3: {L}")
   
   #Now we have L /(x3)=[]
   J_val=[]
   for i in range(3):
       filtered_df = df_J3[df_J3['x3'] == L[i]]
       J_val.append(int(filtered_df['J3'].values[0]))
   L=[]    
   print(f"J3_curr : {J_val}")
   expr1 = 2 * abs(l) + abs(u[0]) + J_val[0]
   expr2 = 2 * abs(l) + abs(u[1]) + J_val[1]
   expr3 = 2 * abs(l) + abs(u[2]) + J_val[2]
   j_expressions=[expr1, expr2, expr3]
   J_select=min(j_expressions)
   u_curr_ind=j_expressions.index(J_select)
   u_curr=u[u_curr_ind]
   u2[iteration]=u_curr
   print(f"J* for x2: {J_select}")
   print(f"Corresponding u for min J_select: {u_curr}")
   J2[iteration]=J_select
   iteration+=1
   print(J2)

print("_______________________________________________________________") 
print(J2)    
print(u2)       

_______________________________________________________________
At x2 = -2
x3 set for J3: [2, 2, 2]
J3_curr : [4, 4, 4]
J* for x2: 8
Corresponding u for min J_select: 0
[8. 0. 0. 0. 0.]
_______________________________________________________________
At x2 = -1
x3 set for J3: [1, 2, 2]
J3_curr : [1, 4, 4]
J* for x2: 4
Corresponding u for min J_select: -1
[8. 4. 0. 0. 0.]
_______________________________________________________________
At x2 = 0
x3 set for J3: [0, 1, 2]
J3_curr : [0, 1, 4]
J* for x2: 1
Corresponding u for min J_select: -1
[8. 4. 1. 0. 0.]
_______________________________________________________________
At x2 = 1
x3 set for J3: [-1, 0, 1]
J3_curr : [1, 0, 1]
J* for x2: 2
Corresponding u for min J_select: 0
[8. 4. 1. 2. 0.]
_______________________________________________________________
At x2 = 2
x3 set for J3: [-2, -1, 0]
J3_curr : [4, 1, 0]
J* for x2: 5
Corresponding u for min J_select: 0
[8. 4. 1. 2. 5.]
_______________________________________________________________
[8. 

In [20]:
data2 = {
    'x2': x,
    'J2': J2,
    'u2': u2,
    'x3': x,
    'J3': J3    
}

df_J2 = pd.DataFrame(data2) 
print(df_J2)

   x2   J2   u2  x3  J3
0  -2  8.0  0.0  -2   4
1  -1  4.0 -1.0  -1   1
2   0  1.0 -1.0   0   0
3   1  2.0  0.0   1   1
4   2  5.0  0.0   2   4


In [21]:
L=[]
iteration=0
for l in x:
   print("_______________________________________________________________")
   print(f"At x1 = {l}")
   for k in u:
       l2=-1*(l)+1+k
       if l2>2:
           l2=2
           L.append(int(l2))
       elif l2<-2:
           l2=-2
           L.append(int(l2))
       else:
           L.append(int(l2)) 
    
   print(f"x2 set for J2: {L}")
   
   #Now we have L /(x3)=[]
   J_val=[]
   for i in range(3):
       filtered_df = df_J2[df_J2['x3'] == L[i]]
       J_val.append(int(filtered_df['J2'].values[0]))
   L=[]    
   print(f"J3_curr : {J_val}")
   expr1 = 2 * abs(l) + abs(u[0]) + J_val[0]
   expr2 = 2 * abs(l) + abs(u[1]) + J_val[1]
   expr3 = 2 * abs(l) + abs(u[2]) + J_val[2]
   j_expressions=[expr1, expr2, expr3]
   J_select=min(j_expressions)
   u_curr_ind=j_expressions.index(J_select)
   u_curr=u[u_curr_ind]
   u1[iteration]=u_curr
   print(f"J* for x2: {J_select}")
   print(f"Corresponding u for min J_select: {u_curr}")
   J1[iteration]=J_select
   iteration+=1
   print(J1)

print("_______________________________________________________________") 
print(J1)    
print(u1)       

_______________________________________________________________
At x1 = -2
x2 set for J2: [2, 2, 2]
J3_curr : [5, 5, 5]
J* for x2: 9
Corresponding u for min J_select: 0
[9. 0. 0. 0. 0.]
_______________________________________________________________
At x1 = -1
x2 set for J2: [1, 2, 2]
J3_curr : [2, 5, 5]
J* for x2: 5
Corresponding u for min J_select: -1
[9. 5. 0. 0. 0.]
_______________________________________________________________
At x1 = 0
x2 set for J2: [0, 1, 2]
J3_curr : [1, 2, 5]
J* for x2: 2
Corresponding u for min J_select: -1
[9. 5. 2. 0. 0.]
_______________________________________________________________
At x1 = 1
x2 set for J2: [-1, 0, 1]
J3_curr : [4, 1, 2]
J* for x2: 3
Corresponding u for min J_select: 0
[9. 5. 2. 3. 0.]
_______________________________________________________________
At x1 = 2
x2 set for J2: [-2, -1, 0]
J3_curr : [8, 4, 1]
J* for x2: 6
Corresponding u for min J_select: 1
[9. 5. 2. 3. 6.]
_______________________________________________________________
[9. 

In [22]:
data1 = {
    'x1': x,
    'J1': J1,
    'u1': u1,
    'x2': x,
    'J2': J2,
    'u2': u2,
    'x3': x,
    'J3': J3    
}

df_J1 = pd.DataFrame(data1) 
print(df_J1)

   x1   J1   u1  x2   J2   u2  x3  J3
0  -2  9.0  0.0  -2  8.0  0.0  -2   4
1  -1  5.0 -1.0  -1  4.0 -1.0  -1   1
2   0  2.0 -1.0   0  1.0 -1.0   0   0
3   1  3.0  0.0   1  2.0  0.0   1   1
4   2  6.0  1.0   2  5.0  0.0   2   4


In [23]:
L=[]
iteration=0
for l in x:
   print("_______________________________________________________________")
   print(f"At x0 = {l}")
   for k in u:
       l2=-1*(l)+1+k
       if l2>2:
           l2=2
           L.append(int(l2))
       elif l2<-2:
           l2=-2
           L.append(int(l2))
       else:
           L.append(int(l2)) 
    
   print(f"x1 set for J1: {L}")
   
   #Now we have L /(x3)=[]
   J_val=[]
   for i in range(3):
       filtered_df = df_J1[df_J1['x3'] == L[i]]
       J_val.append(int(filtered_df['J1'].values[0]))
   L=[]    
   print(f"J1_curr : {J_val}")
   expr1 = 2 * abs(l) + abs(u[0]) + J_val[0]
   expr2 = 2 * abs(l) + abs(u[1]) + J_val[1]
   expr3 = 2 * abs(l) + abs(u[2]) + J_val[2]
   j_expressions=[expr1, expr2, expr3]
   J_select=min(j_expressions)
   u_curr_ind=j_expressions.index(J_select)
   u_curr=u[u_curr_ind]
   u0[iteration]=u_curr
   print(f"J* for x2: {J_select}")
   print(f"Corresponding u for min J_select: {u_curr}")
   J0[iteration]=J_select
   iteration+=1
   print(J0)

print("_______________________________________________________________") 
print(J0)    
print(u0)       

_______________________________________________________________
At x0 = -2
x1 set for J1: [2, 2, 2]
J1_curr : [6, 6, 6]
J* for x2: 10
Corresponding u for min J_select: 0
[10.  0.  0.  0.  0.]
_______________________________________________________________
At x0 = -1
x1 set for J1: [1, 2, 2]
J1_curr : [3, 6, 6]
J* for x2: 6
Corresponding u for min J_select: -1
[10.  6.  0.  0.  0.]
_______________________________________________________________
At x0 = 0
x1 set for J1: [0, 1, 2]
J1_curr : [2, 3, 6]
J* for x2: 3
Corresponding u for min J_select: -1
[10.  6.  3.  0.  0.]
_______________________________________________________________
At x0 = 1
x1 set for J1: [-1, 0, 1]
J1_curr : [5, 2, 3]
J* for x2: 4
Corresponding u for min J_select: 0
[10.  6.  3.  4.  0.]
_______________________________________________________________
At x0 = 2
x1 set for J1: [-2, -1, 0]
J1_curr : [9, 5, 2]
J* for x2: 7
Corresponding u for min J_select: 1
[10.  6.  3.  4.  7.]
__________________________________________

In [24]:
data0 = {
    'x0': x,
    'J0': J0,
    'u0': u0,
    'x1': x,
    'J1': J1,
    'u1': u1,
    'x2': x,
    'J2': J2,
    'u2': u2,
    'x3': x,
    'J3': J3    
}

df_J0 = pd.DataFrame(data0) 
print(df_J0)

   x0    J0   u0  x1   J1   u1  x2   J2   u2  x3  J3
0  -2  10.0  0.0  -2  9.0  0.0  -2  8.0  0.0  -2   4
1  -1   6.0 -1.0  -1  5.0 -1.0  -1  4.0 -1.0  -1   1
2   0   3.0 -1.0   0  2.0 -1.0   0  1.0 -1.0   0   0
3   1   4.0  0.0   1  3.0  0.0   1  2.0  0.0   1   1
4   2   7.0  1.0   2  6.0  1.0   2  5.0  0.0   2   4


b) What is the sequence of control actions, states, and the optimal cost if $ x_0 = 0 $, if $ x_0 = -2 $, and if $ x_0 = 2 $?

Solution:$\\$
$$
x_{n+1} = 
\begin{cases} 
    -x_n + 1 + u_n & \text{if } -2 \leq -x_n + 1 + u_n \leq 2 \\
    2 & \text{if } -x_n + 1 + u_n > 2 \\
    -2 & \text{else}
\end{cases}
$$


In [25]:
# To find the sequence of control actions, states and the optimal costs
# At x0=0

x_seq_0=[]
u_seq_0=[]
J_seq_0=[]
x0_vals=[-2, 0, 2]
#for i in x0_vals:
i=x0_vals[0]
start=0
while True:
        
    clipped_row=df_J0[df_J0[f'x{start}']==i]
    x_curr=int(clipped_row[f'x{start}'].values[0])  #-2   
    x_seq_0.append(x_curr)
    J_seq_0.append(int(clipped_row[f'J{start}'].values[0]))
    
    
    exit=(f'u{start}')
    if exit=='u3':
        break
    
    u_curr=int(clipped_row[f'u{start}'].values[0])  # 0
    u_seq_0.append(u_curr)
    
    
    i=-x_curr+1+u_curr
    
    if i<-2:
        i=-2
    elif i>2:
        i=2
    else:
        i=i
    
    start+=1
    
    
# Print the sequences
print(f"\nSequences for initial state x0 = 0:")
print(f"x_seq: {x_seq_0}")
print(f"J_seq: {J_seq_0}")
print(f"u_seq: {u_seq_0}")   



Sequences for initial state x0 = 0:
x_seq: [-2, 2, 0, 0]
J_seq: [10, 6, 1, 0]
u_seq: [0, 1, -1]


In [26]:
x_seq_1=[]
u_seq_1=[]
J_seq_1=[]
x0_vals=[-2, 0, 2]
#for i in x0_vals:
i=x0_vals[1]
start=0
while True:
        
    clipped_row=df_J0[df_J0[f'x{start}']==i]
    x_curr=int(clipped_row[f'x{start}'].values[0])  #-2   
    x_seq_1.append(x_curr)
    J_seq_1.append(int(clipped_row[f'J{start}'].values[0]))
    
    
    exit=(f'u{start}')
    if exit=='u3':
        break
    
    u_curr=int(clipped_row[f'u{start}'].values[0])  # 0
    u_seq_1.append(u_curr)
    
    
    i=-x_curr+1+u_curr
    
    if i<-2:
        i=-2
    elif i>2:
        i=2
    else:
        i=i
    
    start+=1
    
    
# Print the sequences
print(f"\nSequences for initial state x0 = 1:")
print(f"x_seq: {x_seq_1}")
print(f"J_seq: {J_seq_1}")
print(f"u_seq: {u_seq_1}")   


Sequences for initial state x0 = 1:
x_seq: [0, 0, 0, 0]
J_seq: [3, 2, 1, 0]
u_seq: [-1, -1, -1]


In [27]:
x_seq_2=[]
u_seq_2=[]
J_seq_2=[]
x0_vals=[-2, 0, 2]
#for i in x0_vals:
i=x0_vals[2]
start=0
while True:
        
    clipped_row=df_J0[df_J0[f'x{start}']==i]
    x_curr=int(clipped_row[f'x{start}'].values[0])  #-2   
    x_seq_2.append(x_curr)
    J_seq_2.append(int(clipped_row[f'J{start}'].values[0]))
    
    
    exit=(f'u{start}')
    if exit=='u3':
        break
    
    u_curr=int(clipped_row[f'u{start}'].values[0])  # 0
    u_seq_2.append(u_curr)
    
    
    i=-x_curr+1+u_curr
    
    if i<-2:
        i=-2
    elif i>2:
        i=2
    else:
        i=i
    
    start+=1
    

# Print the sequences
print(f"\nSequences for initial state x0 = 2:")
print(f"x_seq: {x_seq_2}")
print(f"J_seq: {J_seq_2}")
print(f"u_seq: {u_seq_2}")    



Sequences for initial state x0 = 2:
x_seq: [2, 0, 0, 0]
J_seq: [7, 2, 1, 0]
u_seq: [1, -1, -1]


c) Assume now that the constant term 1 in the previous dynamics can sometimes be 0 with probability 0.4. We can now write the dynamics as

$$
x_{n+1} = 
\begin{cases} 
    -x_n + \omega_n + u_n & \text{if } -2 \leq -x_n + \omega_n + u_n \leq 2 \\
    2 & \text{if } -x_n + \omega_n + u_n > 2 \\
    -2 & \text{else}
\end{cases}
$$

where $ x_n \in \{-2, -1, 0, 1, 2\} $, $ u_n \in \{-1, 0, 1\} $ and $ \omega_n \in \{0, 1\} $ is a random variable with probability distribution $ p(\omega_n = 0) = 0.4 $, $ p(\omega_n = 1) = 0.6 $. The cost function to minimize becomes

$$
J = E \left( \sum_{k=0}^2 \left( 2|x_k| + |u_k| + x_3^2 \right) \right)
$$

Use the dynamic programming algorithm to solve the finite horizon optimal control problem that minimizes \( J \). Show the different steps of the algorithm and present the results in a table including the cost-to-go and the optimal control at every stage.


In [28]:
u=np.array([-1, 0, 1])
x=np.array([-2,-1,0,1,2])

u2_prob=np.zeros(5)
u1_prob=np.zeros(5)
u0_prob=np.zeros(5)
J2_prob=np.zeros(5)
J1_prob=np.zeros(5)
J0_prob=np.zeros(5)

J3=[]
for i in x:
    i*=i
    J3.append(i)
    
data3_prob = {
    'x3': x,
    'J3': J3
}

df_J3_prob = pd.DataFrame(data3_prob)   
print(df_J3_prob)


   x3  J3
0  -2   4
1  -1   1
2   0   0
3   1   1
4   2   4


In [29]:
L0=[]
L1=[]
iteration=0
for l in x:
   print("_______________________________________________________________")
   print(f"At x2 = {l}")
   
   # When omega=0; P(omega)=0.4
   for k in u:
       xk_L0=-1*(l)+k
       if xk_L0>2:
           xk_L0=2
           L0.append(int(xk_L0))
       elif xk_L0<-2:
           xk_L0=-2
           L0.append(int(xk_L0))
       else:
           L0.append(int(xk_L0)) 
    
   print(f"x3 set for J3 at omega=0: {L0}")
   
   # When omega=1; P(omega)=0.6
   for k in u:
       xk_L1=-1*(l)+1+k
       if xk_L1>2:
           xk_L1=2
           L1.append(int(xk_L1))
       elif xk_L1<-2:
           xk_L1=-2
           L1.append(int(xk_L1))
       else:
           L1.append(int(xk_L1)) 
    
   print(f"x3 set for J3 at omega=1: {L1}")
   
   #Now we have L /(x3)=[]
   J_val0=[]
   for i in range(3):
       filtered_df_omega0 = df_J3_prob[df_J3_prob['x3'] == L0[i]]
       J_val0.append(int(filtered_df_omega0['J3'].values[0]))
       
   J_val1=[]
   for i in range(3):
       filtered_df_omega1 = df_J3_prob[df_J3_prob['x3'] == L1[i]]
       J_val1.append(int(filtered_df_omega1['J3'].values[0]))
       
   L0=[]
   L1=[]   
   
   expr1 = 0.4*(2 * abs(l) + abs(u[0]) + J_val0[0])+0.6*(2 * abs(l) + abs(u[0]) + J_val1[0])
   expr2 = 0.4*(2 * abs(l) + abs(u[1]) + J_val0[1])+0.6*(2 * abs(l) + abs(u[1]) + J_val1[1])
   expr3 = 0.4*(2 * abs(l) + abs(u[2]) + J_val0[2])+0.6*(2 * abs(l) + abs(u[2]) + J_val1[2])
   j_expressions=[expr1, expr2, expr3]
   J_select=min(j_expressions)
   u_curr_ind=j_expressions.index(J_select)
   u_curr=u[u_curr_ind]
   u2_prob[iteration]=u_curr
   print(f"J* for x2: {J_select}")
   print(f"Corresponding u for min J_select: {u_curr}")
   J2_prob[iteration]=J_select
   iteration+=1
   print(J2_prob)

print("_______________________________________________________________") 
print(J2_prob)    
print(u2_prob)       

_______________________________________________________________
At x2 = -2
x3 set for J3 at omega=0: [1, 2, 2]
x3 set for J3 at omega=1: [2, 2, 2]
J* for x2: 7.8
Corresponding u for min J_select: -1
[7.8 0.  0.  0.  0. ]
_______________________________________________________________
At x2 = -1
x3 set for J3 at omega=0: [0, 1, 2]
x3 set for J3 at omega=1: [1, 2, 2]
J* for x2: 3.6
Corresponding u for min J_select: -1
[7.8 3.6 0.  0.  0. ]
_______________________________________________________________
At x2 = 0
x3 set for J3 at omega=0: [-1, 0, 1]
x3 set for J3 at omega=1: [0, 1, 2]
J* for x2: 0.6
Corresponding u for min J_select: 0
[7.8 3.6 0.6 0.  0. ]
_______________________________________________________________
At x2 = 1
x3 set for J3 at omega=0: [-2, -1, 0]
x3 set for J3 at omega=1: [-1, 0, 1]
J* for x2: 2.4000000000000004
Corresponding u for min J_select: 0
[7.8 3.6 0.6 2.4 0. ]
_______________________________________________________________
At x2 = 2
x3 set for J3 at omega=0: [

In [30]:
data2_prob = {
    'x2': x,
    'J2': J2_prob,
    'u2': u2_prob,
    'x3': x,
    'J3': J3    
}

df_J2_prob = pd.DataFrame(data2_prob) 
print(df_J2_prob)

   x2   J2   u2  x3  J3
0  -2  7.8 -1.0  -2   4
1  -1  3.6 -1.0  -1   1
2   0  0.6  0.0   0   0
3   1  2.4  0.0   1   1
4   2  5.4  1.0   2   4


In [31]:
L0=[]
L1=[]
iteration=0
for l in x:
   print("_______________________________________________________________")
   print(f"At x2 = {l}")
   
   # When omega=0; P(omega)=0.4
   for k in u:
       xk_L0=-1*(l)+k
       if xk_L0>2:
           xk_L0=2
           L0.append(int(xk_L0))
       elif xk_L0<-2:
           xk_L0=-2
           L0.append(int(xk_L0))
       else:
           L0.append(int(xk_L0)) 
    
   print(f"x3 set for J3 at omega=0: {L0}")
   
   # When omega=1; P(omega)=0.6
   for k in u:
       xk_L1=-1*(l)+1+k
       if xk_L1>2:
           xk_L1=2
           L1.append(int(xk_L1))
       elif xk_L1<-2:
           xk_L1=-2
           L1.append(int(xk_L1))
       else:
           L1.append(int(xk_L1)) 
    
   print(f"x3 set for J3 at omega=1: {L1}")
   
   #Now we have L /(x3)=[]
   J_val0=[]
   for i in range(3):
       filtered_df_omega0 = df_J2_prob[df_J2_prob['x2'] == L0[i]]
       J_val0.append((filtered_df_omega0['J2'].values[0]))
       
   J_val1=[]
   for i in range(3):
       filtered_df_omega1 = df_J2_prob[df_J2_prob['x2'] == L1[i]]
       J_val1.append((filtered_df_omega1['J2'].values[0]))
       
   L0=[]
   L1=[]   
  
   expr1 = 0.4*(2 * abs(l) + abs(u[0]) + J_val0[0])+0.6*(2 * abs(l) + abs(u[0]) + J_val1[0])
   expr2 = 0.4*(2 * abs(l) + abs(u[1]) + J_val0[1])+0.6*(2 * abs(l) + abs(u[1]) + J_val1[1])
   expr3 = 0.4*(2 * abs(l) + abs(u[2]) + J_val0[2])+0.6*(2 * abs(l) + abs(u[2]) + J_val1[2])
   j_expressions=[expr1, expr2, expr3]
   J_select=min(j_expressions)
   u_curr_ind=j_expressions.index(J_select)
   u_curr=u[u_curr_ind]
   u1_prob[iteration]=u_curr
   print(f"J* for x1: {J_select}")
   print(f"Corresponding u for min J_select: {u_curr}")
   J1_prob[iteration]=J_select
   iteration+=1
   print(J1_prob)

print("_______________________________________________________________") 
print(J1_prob)    
print(u1_prob)       

_______________________________________________________________
At x2 = -2
x3 set for J3 at omega=0: [1, 2, 2]
x3 set for J3 at omega=1: [2, 2, 2]
J* for x1: 9.200000000000001
Corresponding u for min J_select: -1
[9.2 0.  0.  0.  0. ]
_______________________________________________________________
At x2 = -1
x3 set for J3 at omega=0: [0, 1, 2]
x3 set for J3 at omega=1: [1, 2, 2]
J* for x1: 4.680000000000001
Corresponding u for min J_select: -1
[9.2  4.68 0.   0.   0.  ]
_______________________________________________________________
At x2 = 0
x3 set for J3 at omega=0: [-1, 0, 1]
x3 set for J3 at omega=1: [0, 1, 2]
J* for x1: 1.6800000000000002
Corresponding u for min J_select: 0
[9.2  4.68 1.68 0.   0.  ]
_______________________________________________________________
At x2 = 1
x3 set for J3 at omega=0: [-2, -1, 0]
x3 set for J3 at omega=1: [-1, 0, 1]
J* for x1: 3.8
Corresponding u for min J_select: 0
[9.2  4.68 1.68 3.8  0.  ]
__________________________________________________________

In [32]:
data1_prob = {
    'x1': x,
    'J1': J1_prob,
    'u1': u1_prob,
    'x2': x,
    'J2': J2_prob,
    'u2': u2_prob,
    'x3': x,
    'J3': J3    
}

df_J1_prob = pd.DataFrame(data1_prob) 
print(df_J1_prob)

   x1    J1   u1  x2   J2   u2  x3  J3
0  -2  9.20 -1.0  -2  7.8 -1.0  -2   4
1  -1  4.68 -1.0  -1  3.6 -1.0  -1   1
2   0  1.68  0.0   0  0.6  0.0   0   0
3   1  3.80  0.0   1  2.4  0.0   1   1
4   2  6.80  1.0   2  5.4  1.0   2   4


In [33]:
L0=[]
L1=[]
iteration=0
for l in x:
   print("_______________________________________________________________")
   print(f"At x2 = {l}")
   
   # When omega=0; P(omega)=0.4
   for k in u:
       xk_L0=-1*(l)+k
       if xk_L0>2:
           xk_L0=2
           L0.append(int(xk_L0))
       elif xk_L0<-2:
           xk_L0=-2
           L0.append(int(xk_L0))
       else:
           L0.append(int(xk_L0)) 
    
   print(f"x3 set for J3 at omega=0: {L0}")
   
   # When omega=1; P(omega)=0.6
   for k in u:
       xk_L1=-1*(l)+1+k
       if xk_L1>2:
           xk_L1=2
           L1.append(int(xk_L1))
       elif xk_L1<-2:
           xk_L1=-2
           L1.append(int(xk_L1))
       else:
           L1.append(int(xk_L1)) 
    
   print(f"x3 set for J3 at omega=1: {L1}")
   
   #Now we have L /(x3)=[]
   J_val0=[]
   for i in range(3):
       filtered_df_omega0 = df_J1_prob[df_J1_prob['x1'] == L0[i]]
       J_val0.append((filtered_df_omega0['J1'].values[0]))
       
   J_val1=[]
   for i in range(3):
       filtered_df_omega1 = df_J1_prob[df_J1_prob['x1'] == L1[i]]
       J_val1.append((filtered_df_omega1['J1'].values[0]))
       
   L0=[]
   L1=[]   
   
   expr1 = 0.4*(2 * abs(l) + abs(u[0]) + J_val0[0])+0.6*(2 * abs(l) + abs(u[0]) + J_val1[0])
   expr2 = 0.4*(2 * abs(l) + abs(u[1]) + J_val0[1])+0.6*(2 * abs(l) + abs(u[1]) + J_val1[1])
   expr3 = 0.4*(2 * abs(l) + abs(u[2]) + J_val0[2])+0.6*(2 * abs(l) + abs(u[2]) + J_val1[2])
   j_expressions=[expr1, expr2, expr3]
   J_select=min(j_expressions)
   u_curr_ind=j_expressions.index(J_select)
   u_curr=u[u_curr_ind]
   u0_prob[iteration]=u_curr
   print(f"J* for x1: {J_select}")
   print(f"Corresponding u for min J_select: {u_curr}")
   J0_prob[iteration]=J_select
   iteration+=1
   print(J0_prob)

print("_______________________________________________________________") 
print(J0_prob)    
print(u0_prob)       

_______________________________________________________________
At x2 = -2
x3 set for J3 at omega=0: [1, 2, 2]
x3 set for J3 at omega=1: [2, 2, 2]
J* for x1: 10.600000000000001
Corresponding u for min J_select: -1
[10.6  0.   0.   0.   0. ]
_______________________________________________________________
At x2 = -1
x3 set for J3 at omega=0: [0, 1, 2]
x3 set for J3 at omega=1: [1, 2, 2]
J* for x1: 5.952
Corresponding u for min J_select: -1
[10.6    5.952  0.     0.     0.   ]
_______________________________________________________________
At x2 = 0
x3 set for J3 at omega=0: [-1, 0, 1]
x3 set for J3 at omega=1: [0, 1, 2]
J* for x1: 2.952
Corresponding u for min J_select: 0
[10.6    5.952  2.952  0.     0.   ]
_______________________________________________________________
At x2 = 1
x3 set for J3 at omega=0: [-2, -1, 0]
x3 set for J3 at omega=1: [-1, 0, 1]
J* for x1: 4.880000000000001
Corresponding u for min J_select: 0
[10.6    5.952  2.952  4.88   0.   ]
_________________________________

In [34]:
data0_prob = {
    'x0': x,
    'J0': J0_prob,
    'u0': u0_prob,
    'x1': x,
    'J1': J1_prob,
    'u1': u1_prob,
    'x2': x,
    'J2': J2_prob,
    'u2': u2_prob,
    'x3': x,
    'J3': J3    
}

df_J0_prob = pd.DataFrame(data0_prob) 
print(df_J0_prob)

   x0      J0   u0  x1    J1   u1  x2   J2   u2  x3  J3
0  -2  10.600 -1.0  -2  9.20 -1.0  -2  7.8 -1.0  -2   4
1  -1   5.952 -1.0  -1  4.68 -1.0  -1  3.6 -1.0  -1   1
2   0   2.952  0.0   0  1.68  0.0   0  0.6  0.0   0   0
3   1   4.880  0.0   1  3.80  0.0   1  2.4  0.0   1   1
4   2   7.880  1.0   2  6.80  1.0   2  5.4  1.0   2   4


d) Compare the costs and optimal control from the deterministic and probabilistic models and explain where, in your opinion, the differences come from.

In [35]:
print("Deterministic J")
print(df_J0)
print("Probailistic J")
print(df_J0_prob)

Deterministic J
   x0    J0   u0  x1   J1   u1  x2   J2   u2  x3  J3
0  -2  10.0  0.0  -2  9.0  0.0  -2  8.0  0.0  -2   4
1  -1   6.0 -1.0  -1  5.0 -1.0  -1  4.0 -1.0  -1   1
2   0   3.0 -1.0   0  2.0 -1.0   0  1.0 -1.0   0   0
3   1   4.0  0.0   1  3.0  0.0   1  2.0  0.0   1   1
4   2   7.0  1.0   2  6.0  1.0   2  5.0  0.0   2   4
Probailistic J
   x0      J0   u0  x1    J1   u1  x2   J2   u2  x3  J3
0  -2  10.600 -1.0  -2  9.20 -1.0  -2  7.8 -1.0  -2   4
1  -1   5.952 -1.0  -1  4.68 -1.0  -1  3.6 -1.0  -1   1
2   0   2.952  0.0   0  1.68  0.0   0  0.6  0.0   0   0
3   1   4.880  0.0   1  3.80  0.0   1  2.4  0.0   1   1
4   2   7.880  1.0   2  6.80  1.0   2  5.4  1.0   2   4


### a. Handling of Uncertainty and Cost Calculations

The **deterministic model** assumes full predictability in the system's evolution, leading to decisions that may incur higher costs by not adapting to potential variations. In contrast, the **probabilistic model** incorporates uncertainty by considering multiple possible outcomes with associated probabilities, optimizing for expected costs and potentially resulting in lower average costs. By leveraging probability distributions, the probabilistic model balances decisions across likely scenarios, which can produce a more efficient control strategy than the deterministic approach that may overcompensate for worst-case scenarios.

### b. Optimal Control Strategy and Consistency

In the **probabilistic model**, adjustments in controls—such as shifting $u_0$ from $0.0$ to $-1.0$ at $x_0 = -2$—show an adaptive approach that minimizes expected costs by anticipating possible variations. However, for most states, both models agree on the optimal control, suggesting that under certain conditions, the presence of uncertainty does not significantly impact the decision-making process, leading to consistency in control strategies.
